"""consolidate notes to full jsonb and add tags and collections

Revision ID: 17db4e32f774
Revises: d549dbc882b3
Create Date: 2025-11-14 16:10:07.313665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '17db4e32f774'
down_revision: Union[str, Sequence[str], None] = 'd549dbc882b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Check if tables exist before creating
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    existing_tables = inspector.get_table_names()

    # Create tags table if it doesn't exist
    if 'tags' not in existing_tables:
        op.create_table('tags',
            sa.Column('id', sa.UUID(), nullable=False),
            sa.Column('name', sa.String(), nullable=False),
            sa.Column('color', sa.String(), nullable=True),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('name')
        )

    # Create video_tags junction table if it doesn't exist
    if 'video_tags' not in existing_tables:
        op.create_table('video_tags',
            sa.Column('video_id', sa.UUID(), nullable=False),
            sa.Column('tag_id', sa.UUID(), nullable=False),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
            sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
            sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
            sa.PrimaryKeyConstraint('video_id', 'tag_id')
        )

    op.create_unique_constraint(None, 'collections', ['name'])
    op.create_index(op.f('ix_transcriptions_video_id'), 'transcriptions', ['video_id'], unique=True)
    op.drop_constraint(op.f('transcriptions_video_id_fkey'), 'transcriptions', type_='foreignkey')
    op.create_foreign_key(None, 'transcriptions', 'videos', ['video_id'], ['id'], ondelete='CASCADE')
    op.drop_column('transcriptions', 'notes_model_used')
    op.drop_column('transcriptions', 'notes_processing_time')
    op.add_column('videos', sa.Column('collection_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_videos_collection_id'), 'videos', ['collection_id'], unique=False)
    op.create_index(op.f('ix_videos_status'), 'videos', ['status'], unique=False)
    op.create_index(op.f('ix_videos_uploaded_at'), 'videos', ['uploaded_at'], unique=False)
    op.create_foreign_key(None, 'videos', 'collections', ['collection_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'videos', type_='foreignkey')
    op.drop_index(op.f('ix_videos_uploaded_at'), table_name='videos')
    op.drop_index(op.f('ix_videos_status'), table_name='videos')
    op.drop_index(op.f('ix_videos_collection_id'), table_name='videos')
    op.drop_column('videos', 'collection_id')
    op.add_column('transcriptions', sa.Column('notes_processing_time', postgresql.INTERVAL(), autoincrement=False, nullable=True))
    op.add_column('transcriptions', sa.Column('notes_model_used', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'transcriptions', type_='foreignkey')
    op.create_foreign_key(op.f('transcriptions_video_id_fkey'), 'transcriptions', 'videos', ['video_id'], ['id'])
    op.drop_index(op.f('ix_transcriptions_video_id'), table_name='transcriptions')
    op.drop_constraint(None, 'collections', type_='unique')

    # Drop tags tables
    op.drop_table('video_tags')
    op.drop_table('tags')
    # ### end Alembic commands ###
