"""Add duration_seconds to videos table

Revision ID: 4b0757f4fba5
Revises: 17db4e32f774
Create Date: 2025-11-14 23:20:24.038845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b0757f4fba5'
down_revision: Union[str, Sequence[str], None] = '17db4e32f774'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('duration_seconds', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'duration_seconds')
    # ### end Alembic commands ###
