"""add deleted_at to videos table

Revision ID: 4cdcc640fbd5
Revises: 03ea02614a53
Create Date: 2025-11-20 15:46:41.807895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cdcc640fbd5'
down_revision: Union[str, Sequence[str], None] = '03ea02614a53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_videos_deleted_at'), 'videos', ['deleted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_videos_deleted_at'), table_name='videos')
    op.drop_column('videos', 'deleted_at')
    # ### end Alembic commands ###
