"""Add title field to videos table

Revision ID: 81743a8eb5f6
Revises: 4b0757f4fba5
Create Date: 2025-11-15 00:03:09.109900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81743a8eb5f6'
down_revision: Union[str, Sequence[str], None] = '4b0757f4fba5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'title')
    # ### end Alembic commands ###
