"""add hls fields to videos

Revision ID: a9412bb22018
Revises: d74216e8c50d
Create Date: 2025-11-20 07:15:08.431143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9412bb22018'
down_revision: Union[str, Sequence[str], None] = 'd74216e8c50d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('hls_playlist_key', sa.String(), nullable=True))
    op.add_column('videos', sa.Column('hls_status', sa.Enum('generating', 'ready', 'failed', name='hlsstatus'), nullable=True))
    op.add_column('videos', sa.Column('hls_generated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('videos', sa.Column('hls_error_message', sa.Text(), nullable=True))
    op.create_index(op.f('ix_videos_hls_playlist_key'), 'videos', ['hls_playlist_key'], unique=False)
    op.create_index(op.f('ix_videos_hls_status'), 'videos', ['hls_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_videos_hls_status'), table_name='videos')
    op.drop_index(op.f('ix_videos_hls_playlist_key'), table_name='videos')
    op.drop_column('videos', 'hls_error_message')
    op.drop_column('videos', 'hls_generated_at')
    op.drop_column('videos', 'hls_status')
    op.drop_column('videos', 'hls_playlist_key')
    # ### end Alembic commands ###
