"""add r2_key to videos table

Revision ID: d74216e8c50d
Revises: a1b2c3d4e5f6
Create Date: 2025-11-20 06:47:01.187485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd74216e8c50d'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('r2_key', sa.String(), nullable=True))
    op.create_index(op.f('ix_videos_r2_key'), 'videos', ['r2_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_videos_r2_key'), table_name='videos')
    op.drop_column('videos', 'r2_key')
    # ### end Alembic commands ###
