"""Add YouTube support fields to videos table

Revision ID: fe2fbd5c0651
Revises: 6938b4d9027f
Create Date: 2025-11-16 16:31:30.329331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe2fbd5c0651'
down_revision: Union[str, Sequence[str], None] = '6938b4d9027f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('source_type', sa.Enum('upload', 'youtube', name='sourcetype'), nullable=False, server_default='upload'))
    op.add_column('videos', sa.Column('youtube_url', sa.String(), nullable=True))
    op.create_index(op.f('ix_videos_source_type'), 'videos', ['source_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_videos_source_type'), table_name='videos')
    op.drop_column('videos', 'youtube_url')
    op.drop_column('videos', 'source_type')
    # ### end Alembic commands ###
